### ISSUE TITLE
UI Bug on Safari

### ISSUE THREAD

**Issue by hasangokdag** [aburakayaz/suchedule#10]
Safari 12.1.2 on MacOS 10.14.6
<img width="452" src="https://user-images.githubusercontent.com/35078378/65129848-d765ad00-da04-11e9-877a-dc4cc783250c.png">

<img src="https://media.giphy.com/media/SUztVl3aUClxvqsqqf/giphy.gif">

**Comment by aburakayaz** [comment]
@bekorn Can you have a look? I can test it on safari if you have a solution.
