### ISSUE TITLE
Fall 2021-2022 Term

### ISSUE THREAD

**Issue by aliparlakci** [aburakayaz/suchedule#22]
great power comes with great responsibility. sabanci awaits suchedule

**Comment by aliparlakci** [comment]
@aburakayaz

**Comment by aburakayaz** [comment]
@aliparlakci I'm hearing that there is a problem with ME courses. Is there any way you could help me by fixing the data manually? I would really appreciate some help because I'm swamped and I can't edit the json manually for now, yet alone looking for the problem during parsing and try to solve it.

**Comment by aliparlakci** [comment]
i will take a look and try to fix it manually

**Comment by aburakayaz** [comment]
@aliparlakci two of my friends are looking into it, thanks for your enthusiasm tho!

**Comment by aliparlakci** [comment]
I did some changes and pushed it to "fix" branch, you might want to take a look.
